#!/bin/bash
set -e

. script/functions

echo
echo "===> Build hooktftp inside a dev container and copy to /tmp."
pushd src/alpine/builder
smitty docker build --rm -t hooktftp-builder .
smitty sudo rm -f /tmp/hooktftp
smitty docker run --rm -v /tmp:/tmp hooktftp-builder
popd

echo
echo "===> Build a tiny runtime image with hooktftp static binary."
pushd src/alpine/runtime
smitty cp -f /tmp/hooktftp .
echo $WERCKER_BUILD_URL > wercker-build-url
smitty docker build --rm -t hooktftp-runtime .
smitty rm -f hooktftp
popd

echo
echo "===> Build a tiny tftp client image that we use to test."
pushd src/alpine/client
smitty docker build --rm -t tftp .
popd

echo
echo "===> Show image sizes."
docker images | egrep '^(hooktftp|tftp)\b'


echo
echo "WARN: you should docker tag the runtime image"
echo "WARN: you can safely remove the other images"
echo
