#!/bin/sh
set -e

. script/functions
. test/functions.bash

echo
echo "===> Clean up from previous test runs."
cids="
  tftp
  tftpd
  downloads
  fixtures
"
for cid in $cids; do
  smitty docker_rm $cid || :
done

echo
echo "===> Create data container in which to download test files."
smitty docker create --name downloads -v /home/user alpine:3.3 true
# Ensure the tftp client user has permissions on the volume.
smitty docker run --rm --volumes-from downloads alpine:3.3 chown -R 1000:1000 /home/user

echo
echo "===> Create data container for fixtures."
smitty docker create --name fixtures hooktftp-fixtures true

echo
echo "===> Start hooktftp server."
smitty docker run -d -p 69:69/udp --volumes-from fixtures --name tftpd hooktftp-runtime
ip=$(docker inspect --format '{{.NetworkSettings.IPAddress}}' tftpd | tr -d '\r')
export ip
echo "Server is up at $ip"

echo
echo "===> Run BATS tests."
bats --tap test/*.bats
