#!/bin/sh
set -e

. script/functions

docker_rm() {
  cid=$1
  docker rm -f $cid &> /dev/null || :
}

tftp_get() {
  host=$1
  file=$2
  smitty docker run --rm --volumes-from downloads tftp $1 -c get $2
}

echo
echo "===> Clean up from previous test runs."
cids="
  tftp
  tftpd
  downloads
  fixtures
"
for cid in $cids; do
  [ "$WERCKER" = "true" ] || docker_rm $cid
done

echo
echo "===> Create data container in which to download test files."
smitty docker create --name downloads -v /home/user alpine:3.3 true
# Ensure the tftp client user has permissions on the volume.
smitty docker run --rm --volumes-from downloads alpine:3.3 chown -R 1000:1000 /home/user

echo
echo "===> Create data container for fixtures."
smitty docker create --name fixtures hooktftp-fixtures true

echo
echo "===> Start hooktftp server."
smitty docker run -d -p 69:69/udp --volumes-from fixtures --name tftpd hooktftp-runtime
ip=$(docker inspect --format '{{.NetworkSettings.IPAddress}}' tftpd | tr -d '\r')
echo "Server is up at $ip"

echo
echo "===> Test that hooktftp binary is owned by root:root"
uidgid=$(docker run --rm --entrypoint /bin/sh hooktftp-runtime -c "stat -c %u:%g /usr/bin/hooktftp" | tr -d '=r')
test '0:0' = "$uidgid" && echo OK

echo
echo "===> Test that we can download files via tftp client."
echo "---> site/menu"
tftp_get $ip site/menu
docker run --rm --volumes-from downloads alpine:3.3 test -r /home/user/menu
echo
echo "---> pxelinux.0"
tftp_get $ip pxelinux.0
docker run --rm --volumes-from downloads alpine:3.3 test -s /home/user/pxelinux.0
echo
echo "---> non-existent-file"
tftp_get $ip non-existent-file
echo
echo "---> pxelinux.cfg/default"
tftp_get $ip pxelinux.cfg/default
docker run --rm --volumes-from downloads alpine:3.3 test -s /home/user/default
echo
echo "---> pxelinux.cfg/F1.msg"
tftp_get $ip pxelinux.cfg/F1.msg
docker run --rm --volumes-from downloads alpine:3.3 test -s /home/user/F1.msg

echo
echo "===> Show hooktftp server log."
smitty docker logs tftpd

echo
echo "===> Show wercker build URL."
smitty docker run --rm --entrypoint /bin/sh hooktftp-runtime -c "cat /root/wercker-build-url"
