#!/bin/sh
set -e

docker_rm() {
  cid=$1
  docker rm -f $cid &> /dev/null || :
}

tftp_get() {
  host=$1
  file=$2
  docker run --rm -v /tmp/:/home/user/ tftp $1 -c get $2
}

echo
echo "===> Clean up from previous test runs."
sudo rm -f /tmp/menu
cids="
  tftp
  tftpd
"
for cid in $cids; do
  docker_rm $cid
done

echo
echo "===> Start hooktftp server."
docker run -d -p 69:69/udp -v $(pwd)/fixtures:/tftpboot:ro --name tftpd hooktftp-runtime
ip=$(docker inspect --format '{{.NetworkSettings.IPAddress}}' tftpd | tr -d '\r')
echo "Server is up at $ip"

echo
echo "===> Test that hooktftp binary is owned by root:root"
uidgid=$(docker run --rm --entrypoint /bin/sh hooktftp-runtime -c "stat -c %u:%g /usr/bin/hooktftp" | tr -d '=r')
test '0:0' == $uidgid && echo OK

echo
echo "===> Test that we can download a file via tftp client."
echo "---> menu"
tftp_get $ip menu
test -r /tmp/menu
grep 'Sample pxe menu' /tmp/menu
echo
echo "---> non-existent-file"
tftp_get $ip non-existent-file

echo
echo "===> Show hooktftp server log."
docker logs tftpd
