#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Prepare the local dev environment.
# Invoke from the root of the git repo as "ci/bootstrap".
################################################################################
. ci/functions

main() {
  setup_python_path
  install_precommit
}

setup_python_path() {
  info "Check that PATH includes \${PYTHON_PATH}"
  PYTHON_PATH="$(python -c "import site; print(site.USER_BASE)")"
  readonly PYTHON_PATH
  info "\${PYTHON_PATH} is ${PYTHON_PATH}"

  if ! grep "${PYTHON_PATH}/bin" <(printenv PATH) &>/dev/null; then
    run export PATH="${PATH}:${PYTHON_PATH}/bin"
  fi
}

install_precommit() {
  if ! command -v pre-commit &>/dev/null; then
    run pip install --user -Iv --compile --no-cache-dir pre-commit
  fi

  run pre-commit install-hooks
}

main
