#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Prepare the local dev environment.
# Invoke from the root of the git repo as "ci/bootstrap".
################################################################################
. ci/functions

main() {
  setup_python_path
  install_precommit
  add_upstream_git_remote
  fetch_upstream
}

setup_python_path() {
  info "Check that PATH includes \${PYTHON_PATH}"
  if command -v python3 &>/dev/null; then
    python="python3"
  else
    python="python"
  fi
  PYTHON_PATH="$(${python} -c "import site; print(site.USER_BASE)")"
  readonly PYTHON_PATH
  info "\${PYTHON_PATH} is ${PYTHON_PATH}"

  if ! grep "${PYTHON_PATH}/bin" <(printenv PATH) &>/dev/null; then
    run export PATH="${PATH}:${PYTHON_PATH}/bin"
  fi
}

install_precommit() {
  if command -v pip3 &>/dev/null; then
    pip="pip3"
  else
    pip="pip"
  fi
  "${pip}" install \
    --compile \
    --disable-pip-version-check \
    --no-cache-dir \
    --quiet \
    --user \
    --verbose \
    -r ci/requirements.txt

  run pre-commit install-hooks
}

add_upstream_git_remote() {
  if ! git remote show upstream &>/dev/null; then
    git remote add upstream https://github.com/jumanjihouse/docker-hooktftp.git
  fi
}

fetch_upstream() {
  git fetch upstream
}

main
