#!/bin/bash
set -e

. ci/functions

info "Build a tiny runtime image with hooktftp static binary."
pushd src/alpine/builder
run docker build --rm -t hooktftp-runtime .
popd

info "Build a fixtures images that we use to test."
run docker build --rm -t hooktftp-fixtures fixtures/

info "Build a tiny tftp client image that we use to test."
pushd src/alpine/client
run docker build --rm -t tftp .
popd

info "Show image sizes."
docker images | grep -E '^(hooktftp|tftp)\b'

echo
warn "Remember to docker tag the runtime image."
warn "You can safely remove the other images."
echo
