#!/bin/bash
set -e

cat >ci/vars <<EOF
export BUILD_DATE="$(date +%Y%m%dT%H%M)"
export VCS_REF="$(git rev-parse --short HEAD)"
export TAG="$(date +%Y%m%dT%H%M)-git-\${VCS_REF}"

# # This can be a commit or any other git treeish.
export HOOKTFTP_VERSION="8736c5fade98b7bd589d50936ab1ccd41a52eaaa"
EOF

. ci/functions
. ci/vars

info "Build images."
run docker-compose build

info "Show image labels."
docker inspect hooktftp-runtime | jq -M '.[].Config.Labels'

info "Show image sizes."
docker images | grep -E '^(hooktftp|tftp)\b'

echo
warn "Remember to docker tag the runtime image."
warn "You can safely remove the other images."
echo
