#!/bin/bash
set -eEu
set -o pipefail

. ci/vars

# shellcheck disable=SC2154
docker login -u "${user}" -p "${pass}"

# Push pessimistic tag.
run docker tag hooktftp-runtime "jumanjiman/hooktftp:${TAG}"
run docker push "jumanjiman/hooktftp:${TAG}"

# Push optimistic tag.
run docker tag hooktftp-runtime jumanjiman/hooktftp:latest
run docker push jumanjiman/hooktftp:latest

docker logout

# Update microbadger metadata.
info 'Request microbadger to update metadata'
run curl -sS -X POST 'https://hooks.microbadger.com/images/jumanjiman/hooktftp/bg-SgHGCY6MwMUXWe0nWvAtvXjE='
echo
