#!/bin/bash
set -eEu
set -o pipefail

VCS_REF="$(git rev-parse --short HEAD)"
readonly VCS_REF

TAG="$(date +%Y%m%dT%H%M)-git-${VCS_REF}"
readonly TAG

# shellcheck disable=SC2154
docker login -u "${user}" -p "${pass}"

# Push pessimistic tag.
docker tag hooktftp-runtime "jumanjiman/hooktftp:${TAG}"
docker push "jumanjiman/hooktftp:${TAG}"

# Push optimistic tag.
docker tag hooktftp-runtime jumanjiman/hooktftp:latest
docker push jumanjiman/hooktftp:latest

docker logout
