#!/bin/bash
set -eEu
set -o pipefail

. ci/bootstrap
. ci/functions
. ci/vars
. test/functions.bash

info 'Run file checks.'
run pre-commit run --all-files --hook-stage manual

info "Clean up from previous test runs."
run docker-compose down

info "Create data container in which to download test files."
run docker-compose up downloads

info "Start hooktftp server and fixtures container."
run docker-compose up -d tftpd

info "Run BATS tests."
run bats --tap test/*.bats
